DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public;

CREATE TABLE Sucursal (
	idSucursal SERIAL PRIMARY KEY,
	nombre VARCHAR(64) NOT NULL,
	RFC CHAR(13) NOT NULL UNIQUE CHECK (CHAR_LENGTH(RFC) = 13 AND RFC SIMILAR TO '[A-Z0-9]{13}'),
	codigoPostal  CHAR(5) NOT NULL CHECK (CHAR_LENGTH(codigoPostal) = 5 AND codigoPostal SIMILAR TO '[0-9]{5}'),
	estado VARCHAR(30) NOT NULL,
	calle VARCHAR(30) NOT NULL,
	municipio VARCHAR(30) NOT NULL,
	numeroExt INT NOT NULL CHECK (numeroExt > 0),
	colonia VARCHAR(30) NOT NULL,
	telefono CHAR(10) NOT NULL CHECK (CHAR_LENGTH(telefono) = 10 AND telefono SIMILAR TO '[0-9]{10}'),
	correo VARCHAR(64));

CREATE TABLE Persona (
	CURP CHAR(18) NOT NULL UNIQUE CHECK (CHAR_LENGTH(CURP) = 18 AND CURP SIMILAR TO '[A-Z0-9]{18}') PRIMARY KEY ,
	nombre VARCHAR(30) NOT NULL,
    apellidoPaterno VARCHAR(30) NOT NULL,
    apellidoMaterno VARCHAR(30) NOT NULL,
	fechaNacimiento DATE NOT NULL,
	codigoPostal  CHAR(5) NOT NULL CHECK (CHAR_LENGTH(codigoPostal) = 5 AND codigoPostal SIMILAR TO '[0-9]{5}'),
	estado VARCHAR(30) NOT NULL,
	calle VARCHAR(30) NOT NULL,
	municipio VARCHAR(30) NOT NULL,
	numeroExt INT NOT NULL CHECK (numeroExt > 0),
	colonia VARCHAR(30) NOT NULL,
	telefono CHAR(10) NOT NULL CHECK (CHAR_LENGTH(telefono) = 10 AND telefono SIMILAR TO '[0-9]{10}'),
	correo VARCHAR(64)
);
	
CREATE TABLE Empleado (
	CURP CHAR(18) NOT NULL REFERENCES Persona (CURP) ON DELETE CASCADE ON UPDATE CASCADE,
	idTipoEmpleado INT NOT NULL CHECK (IdTipoEmpleado  > 0),
	idSucursal INT NOT NULL CHECK (idSucursal   > 0) REFERENCES Sucursal(idSucursal) ON DELETE CASCADE ON UPDATE CASCADE
	);

CREATE TABLE Repartidor (
	CURP CHAR(18) NOT NULL UNIQUE REFERENCES Persona (CURP) ON DELETE CASCADE ON UPDATE CASCADE,
	tieneTransporte BIT NOT NULL,
	noLicencia CHAR(9) NOT NULL UNIQUE
);

CREATE TABLE Vehiculo (
	idVehiculo SERIAL NOT NULL CHECK (idVehiculo  > 0),
	CURP CHAR(18) NOT NULL REFERENCES Repartidor (CURP) ON DELETE CASCADE ON UPDATE CASCADE,
	tipo INT NOT NULL CHECK (tipo  > 0),
	marca VARCHAR(30) NOT NULL,
	modelo VARCHAR(30) NOT NULL
);

CREATE TABLE Cliente (
	CURP CHAR(18) NOT NULL UNIQUE REFERENCES Persona (CURP) ON DELETE CASCADE ON UPDATE CASCADE,
	puntos INT NOT NULL
);

CREATE TABLE MetodoPago (
	idMetodoPago SERIAL NOT NULL,
 	idTipo INT NOT NULL CHECK (idTipo  > 0),
	CURPCliente CHAR(18) NOT NULL REFERENCES Cliente (CURP) ON DELETE CASCADE ON UPDATE CASCADE
);
